--- Tables to be used in The Balatro of Isaac

BI.VANILLA_JOKERS = {
    -- Vanilla Page 1
    "joker",
    "greedy_joker",
    "lusty_joker",
    "wrathful_joker",
    "gluttenous_joker",
    "jolly",
    "zany",
    "mad",
    "crazy",
    "droll",
    "sly",
    "wily",
    "clever",
    "devious",
    "crafty",

    -- Vanilla Page 2
    "half",
    "stencil",
    "four_fingers",
    "mime",
    "credit_card",
    "ceremonial",
    "banner",
    "mystic_summit",
    "marble",
    "loyalty_card",
    "8_ball",
    "misprint",
    "dusk",
    "raised_fist",
    "chaos",

    -- Vanilla Page 3
    "fibonacci",
    "steel_joker",
    "scary_face",
    "abstract",
    "delayed_gratification",
    "hack",
    "pareidolia",
    "gros_michel",
    "even_steven",
    "odd_todd",
    "scholar",
    "business_card",
    "supernova",
    "ride_the_bus",
    "space",

    -- Vanilla Page 4
    "egg",
    "burglar",
    "blackboard",
    "runner",
    "ice_cream",
    "dna",
    "splash",
    "blue_joker",
    "sixth_sense",
    "constellation",
    "hiker",
    "faceless",
    "green_joker",
    "superposition",
    "todo_list",

    -- Vanilla Page 5
    "cavendish",
    "card_sharp",
    "red_card",
    "madness",
    "square",
    "seance",
    "riff_raff",
    "vampire",
    "shortcut",
    "hologram",
    "vagabond",
    "baron",
    "cloud_9",
    "rocket",
    "obelisk",

    -- Vanilla Page 6
    "midas_mask",
    "luchador",
    "photograph",
    "gift",
    "turtle_bean",
    "erosion",
    "reserved_parking",
    "mail_in_rebate",
    "to_the_moon",
    "hallucination",
    "fortune_teller",
    "juggler",
    "drunkard",
    "stone",
    "golden",

    -- Vanilla Page 7
    "lucky_cat",
    "baseball_card",
    "bull",
    "diet_cola",
    "trading_card",
    "flash_card",
    "popcorn",
    "spare_trousers",
    "ancient_joker",
    "ramen",
    "walkie_talkie",
    "seltzer",
    "castle",
    "smiley_face",
    "campfire",

    -- Vanilla Page 8
    "golden_ticket",
    "mr_bones",
    "acrobat",
    "sock_and_buskin",
    "swashbuckler",
    "troubadour",
    "certificate",
    "smeared_joker",
    "throwback",
    "hanging_chad",
    "rough_gem",
    "bloodstone",
    "arrowhead",
    "onyx_agate",
    "glass_joker",

    -- Vanilla Page 9
    "showman",
    "flower_pot",
    "blueprint",
    "wee",
    "merry_andy",
    "oops",
    "the_idol",
    "seeing_double",
    "matador",
    "hit_the_road",
    "the_duo",
    "the_trio",
    "the_family",
    "the_order",
    "the_tribe",

    -- Vanilla Page 10
    "stuntman",
    "invisible",
    "brainstorm",
    "satellite",
    "shoot_the_moon",
    "drivers_license",
    "cartomancer",
    "astronomer",
    "burnt",
    "bootstraps",
    "canio",
    "triboulet",
    "yorick",
    "chicot",
    "perkeo"
}

BI.ENABLED_JOKERS = {
    -- Page 1
    "page1/sad_onion",
    "page1/inner_eye",
    "page1/spoon_bender",
    "page1/crickets_head",
    "page1/my_reflection",
    "page1/number_one",
    "page1/blood_of_the_martyr",
    "page1/brother_bobby",
    "page1/skatole",
    "page1/halo_of_flies",
    "page1/1up",
    "page1/magic_mushroom",
    "page1/the_virus",
    "page1/roid_rage",
    "page1/less_than_3",

    -- Page 2
    "page2/raw_liver",
    --"page2/skeleton_key", -- Keys still unimplemented
    "page2/a_dollar",
    --"page2/boom", -- Bombs still unimplemented
    "page2/transcendence",
    "page2/the_compass",
    "page2/lunch",
    "page2/dinner",
    "page2/dessert",
    "page2/breakfast",
    "page2/rotten_meat",
    "page2/wooden_spoon",
    "page2/the_belt",
    "page2/moms_underwear",
    "page2/moms_heels",

    -- Page 3
    -- "page3/moms_lipstick",
    -- "page3/wire_coat_hanger",
    -- "page3/the_bible",
    -- "page3/the_book_of_belial",
    -- "page3/the_necronomicon",
    -- "page3/the_poop",
    -- "page3/mr_boom",
    -- "page3/tammys_head",
    -- "page3/moms_bra",
    -- "page3/kamikaze",
    -- "page3/moms_pad",
    -- "page3/bobs_rotten_head",
    -- "page3/teleport",
    -- "page3/yum_heart",
    -- "page3/lucky_foot",

    -- Page 4
    -- "page4/doctors_remote",
    -- "page4/cupids_arrow",
    -- "page4/shoop_da_woop",
    -- "page4/steven",
    -- "page4/pentagram",
    -- "page4/dr_fetus",
    -- "page4/magneto",
    -- "page4/treasure_map",
    -- "page4/moms_eye",
    -- "page4/lemon_mishap",
    -- "page4/distant_admiration",
    -- "page4/book_of_shadows",
    -- "page4/the_ladder",
    -- "page4/charm_of_the_vampire",
    -- "page4/the_battery",

    -- Page 5
    -- "page5/steam_sale",
    -- "page5/anarchist_cookbook",
    -- "page5/the_hourglass",
    -- "page5/sister_maggy",
    -- "page5/technology",
    -- "page5/chocolate_milk",
    -- "page5/growth_hormones",
    -- "page5/mini_mush",
    -- "page5/rosary",
    -- "page5/cube_of_meat",
    -- "page5/a_quarter",
    -- "page5/phd",
    -- "page5/xray_vision",
    -- "page5/my_little_unicorn",
    -- "page5/book_of_revelations",

    -- Page 6
    -- "page6/the_mark",
    -- "page6/the_pact",
    -- "page6/dead_cat",
    -- "page6/lord_of_the_pit",
    -- "page6/the_nail",
    -- "page6/we_need_to_go_deeper",
    -- "page6/deck_of_cards",
    -- "page6/monstros_tooth",
    -- "page6/lokis_horns",
    -- "page6/little_chubby",
    -- "page6/spider_bite",
    -- "page6/the_small_rock",
    -- "page6/spelunker_hat",
    -- "page6/super_bandage",
    -- "page6/the_gamekid",

    -- Page 7
    -- "page7/sack_of_pennies",
    -- "page7/robo_baby",
    -- "page7/little_chad",
    -- "page7/the_book_of_sin",
    -- "page7/the_relic",
    -- "page7/little_gish",
    -- "page7/little_steven",
    -- "page7/the_halo",
    -- "page7/moms_bottle_of_pills",
    -- "page7/the_common_cold",
    -- "page7/the_parasite",
    "page7/the_d6",
    -- "page7/mr_mega",
    -- "page7/pinking_shears",
    -- "page7/the_wafer",

    -- Page 8
    -- "page8/money_equals_power",
    -- "page8/moms_contacts",
    -- "page8/the_bean",
    -- "page8/guardian_angel",
    -- "page8/demon_baby",
    -- "page8/moms_knife",
    -- "page8/ouija_board",
    -- "page8/9_volt",
    -- "page8/dead_bird",
    -- "page8/brimstone",
    -- "page8/blood_bag",
    -- "page8/skinny_odd_mushroom",
    -- "page8/fat_odd_mushroom",
    -- "page8/whore_of_babylon",
    -- "page8/monster_manual",

    -- Page 9
    -- "page9/dead_sea_scrolls",
    -- "page9/bobby_bomb",
    -- "page9/razor_blade",
    -- "page9/forget_me_now",
    -- "page9/forever_alone",
    -- "page9/bucket_of_lard",
    -- "page9/a_pony",
    -- "page9/bomb_bag",
    -- "page9/a_lump_of_coal",
    -- "page9/guppys_paw",
    -- "page9/guppys_tail",
    -- "page9/iv_bag",
    -- "page9/best_friend",
    -- "page9/remote_detonator",
    -- "page9/stigmata",

    -- Page 10
    -- "page10/moms_purse",
    -- "page10/bobs_curse",
    -- "page10/pageant_boy",
    -- "page10/scapular",
    -- "page10/speed_ball",
    -- "page10/bum_friend",
    -- "page10/guppys_head",
    -- "page10/prayer_card",
    -- "page10/notched_axe",
    -- "page10/infestation",
    -- "page10/ipecac",
    -- "page10/tough_love",
    -- "page10/the_mulligan",
    -- "page10/technology_2",
    -- "page10/mutant_spider",

    -- Page 11
    -- "page11/chemical_peel",
    -- "page11/the_peeper",
    -- "page11/habit",
    -- "page11/bloody_lust",
    -- "page11/crystal_ball",
    -- "page11/spirit_of_the_night",
    -- "page11/crack_the_sky",
    -- "page11/ankh",
    -- "page11/celtic_cross",
    -- "page11/ghost_baby",
    -- "page11/the_candle",
    -- "page11/cat_o_nine_tails",
    -- "page11/d20",
    -- "page11/harlequin_baby",
    -- "page11/epic_fetus",

    -- Page 12
    -- "page12/polyphemus",
    -- "page12/daddy_longlegs",
    -- "page12/spider_butt",
    -- "page12/sacrificial_dagger",
    -- "page12/mitre",
    -- "page12/rainbow_baby",
    -- "page12/dads_key",
    -- "page12/stem_cells",
    -- "page12/portable_slot",
    -- "page12/holy_water",
    -- "page12/fate",
    -- "page12/the_black_bean",
    -- "page12/white_pony",
    -- "page12/sacred_heart",
    -- "page12/toothpicks",

    -- Page 13
    -- "page13/holy_grail",
    -- "page13/dead_dove",
    -- "page13/blood_rights",
    -- "page13/guppys_hairball",
    -- "page13/abel",
    -- "page13/smb_super_fan",
    -- "page13/pyro",
    -- "page13/3_dollar_bill",
    -- "page13/telepathy_for_dummies",
    -- "page13/meat",
    -- "page13/magic_8_ball",
    -- "page13/moms_coin_purse",
    -- "page13/squeezy",
    -- "page13/jesus_juice",
    -- "page13/box",

    -- Page 14
    -- "page14/moms_key",
    -- "page14/moms_eyeshadow",
    -- "page14/iron_bar",
    "page14/midas_touch",
    -- "page14/humbleing_bundle",
    -- "page14/fanny_pack",
    -- "page14/sharp_plug",
    -- "page14/the_guillotine",
    -- "page14/ball_of_bandages",
    -- "page14/champion_belt",
    -- "page14/butt_bombs",
    -- "page14/gnawed_leaf",
    -- "page14/spiderbaby",
    -- "page14/guppys_collar",
    -- "page14/lost_contact",

    -- Page 15
    -- "page15/anemic",
    -- "page15/goat_head",
    -- "page15/ceremonial_robes",
    -- "page15/moms_wig",
    -- "page15/placenta",
    -- "page15/old_bandage",
    -- "page15/sad_bombs",
    -- "page15/rubber_cement",
    -- "page15/anti_gravity",
    -- "page15/pyromaniac",
    -- "page15/crickets_body",
    -- "page15/gimpy",
    -- "page15/black_lotus",
    -- "page15/piggy_bank",
    -- "page15/moms_perfume",

    -- Page 16
    -- "page16/monstros_lung",
    -- "page16/abaddon",
    -- "page16/ball_of_tar",
    -- "page16/stop_watch",
    -- "page16/tiny_planet",
    -- "page16/infestation_2",
    -- "page16/e_coli",
    -- "page16/deaths_touch",
    -- "page16/key_piece_1",
    -- "page16/key_piece_2",
    -- "page16/experimental_treatment",
    -- "page16/contract_from_below",
    -- "page16/infamy",
    -- "page16/trinity_shield",
    -- "page16/tech_point_5",

    -- Page 17
    -- "page17/20_20",
    -- "page17/blue_map",
    -- "page17/bffs",
    -- "page17/hive_mind",
    -- "page17/theres_options",
    -- "page17/bogo_bombs",
    -- "page17/starter_deck",
    -- "page17/little_baggy",
    -- "page17/magic_scab",
    -- "page17/blood_clot",
    -- "page17/screw",
    -- "page17/hot_bombs",
    -- "page17/fire_mind",
    -- "page17/missing_no",
    -- "page17/dark_matter",

    -- Page 18
    -- "page18/black_candle",
    -- "page18/proptosis",
    -- "page18/missing_page_2",
    -- "page18/smart_fly",
    -- "page18/dry_baby",
    -- "page18/juicy_sack",
    -- "page18/robo_baby_2",
    -- "page18/rotten_baby",
    -- "page18/headless_baby",
    -- "page18/leech",
    -- "page18/mystery_sack",
    -- "page18/bbf",
    -- "page18/bobs_brain",
    -- "page18/best_bud",
    -- "page18/lil_brimstone",

    -- Page 19
    -- "page19/isaacs_heart",
    -- "page19/lil_haunt",
    -- "page19/dark_bum",
    -- "page19/big_fan",
    -- "page19/sissy_long_legs",
    -- "page19/punching_bag",
    -- "page19/how_to_jump",
    -- "page19/d100",
    "page19/d4",
    -- "page19/d10",
    -- "page19/blank_card",
    -- "page19/book_of_secrets",
    -- "page19/box_of_spiders",
    -- "page19/red_candle",
    -- "page19/the_jar",

    -- Page 20
    -- "page20/flush",
    -- "page20/satanic_bible",
    -- "page20/head_of_krampus",
    -- "page20/butter_bean",
    -- "page20/magic_fingers",
    -- "page20/converter",
    -- "page20/pandoras_box",
    -- "page20/unicorn_stump",
    -- "page20/taurus",
    -- "page20/aries",
    -- "page20/cancer",
    -- "page20/leo",
    -- "page20/virgo",
    -- "page20/libra",
    -- "page20/scorpio",

    -- Page 21
    -- "page21/sagittarius",
    -- "page21/capricorn",
    -- "page21/aquarius",
    -- "page21/pisces",
    -- "page21/eves_mascara",
    -- "page21/judas_shadow",
    -- "page21/maggys_bow",
    -- "page21/holy_mantle",
    -- "page21/thunder_thighs",
    -- "page21/strange_attractor",
    -- "page21/cursed_eye",
    -- "page21/mysterious_liquid",
    -- "page21/gemini",
    -- "page21/cains_other_eye",
    -- "page21/blue_babys_only_friend",

    -- Page 22
    -- "page22/samsons_chains",
    -- "page22/mongo_baby",
    -- "page22/isaacs_tears",
    -- "page22/undefined",
    -- "page22/scissors",
    -- "page22/breath_of_life",
    -- "page22/the_polaroid",
    -- "page22/the_negative",
    -- "page22/the_ludovico_technique",
    -- "page22/soy_milk",
    -- "page22/godhead",
    -- "page22/lazarus_rags",
    -- "page22/the_mind",
    -- "page22/the_body",
    -- "page22/the_soul",

    -- Page 23
    -- "page23/dead_onion",
    -- "page23/broken_watch",
    -- "page23/boomerang",
    -- "page23/safety_pin",
    -- "page23/caffeine_pill",
    -- "page23/torn_photo",
    -- "page23/blue_cap",
    -- "page23/latch_key",
    -- "page23/match_book",
    -- "page23/synthoil",
    -- "page23/a_snack",
    -- "page23/diplopia",
    -- "page23/placebo",
    -- "page23/wooden_nickel",
    -- "page23/toxic_shock",

    -- Page 24
    -- "page24/mega_bean",
    -- "page24/glass_cannon",
    -- "page24/bomber_boy",
    -- "page24/crack_jacks",
    -- "page24/moms_pearls",
    -- "page24/car_battery",
    -- "page24/box_of_friends",
    -- "page24/the_wiz",
    -- "page24/8_inch_nails",
    -- "page24/incubus",
    -- "page24/fates_reward",
    -- "page24/lil_chest",
    -- "page24/sworn_protector",
    -- "page24/friend_zone",
    -- "page24/lost_fly",

    -- Page 25
    -- "page25/scatter_bombs",
    -- "page25/sticky_bombs",
    -- "page25/epiphora",
    -- "page25/continuum",
    -- "page25/mr_dolly",
    -- "page25/curse_of_the_tower",
    -- "page25/charged_baby",
    -- "page25/dead_eye",
    -- "page25/holy_light",
    -- "page25/host_hat",
    -- "page25/restock",
    -- "page25/bursting_sack",
    -- "page25/no_2",
    -- "page25/pupula_duplex",
    -- "page25/pay_to_play",

    -- Page 26
    -- "page26/edens_blessing",
    -- "page26/friendly_ball",
    -- "page26/tear_detonator",
    -- "page26/lil_gurdy",
    -- "page26/bumbo",
    -- "page26/d12",
    -- "page26/censer",
    -- "page26/key_bum",
    -- "page26/rune_bag",
    -- "page26/seraphim",
    -- "page26/betrayal",
    -- "page26/zodiac",
    -- "page26/serpents_kiss",
    -- "page26/marked",
    -- "page26/tech_x",

    -- Page 27
    -- "page27/ventricle_razor",
    -- "page27/tractor_beam",
    -- "page27/gods_flesh",
    -- "page27/maw_of_the_void",
    -- "page27/spear_of_destiny",
    -- "page27/explosivo",
    -- "page27/chaos",
    -- "page27/spider_mod",
    -- "page27/farting_baby",
    -- "page27/gb_bug",
    -- "page27/d8",
    -- "page27/purity",
    -- "page27/athame",
    "page27/empty_vessel",
    -- "page27/evil_eye",

    -- Page 28
    -- "page28/lusty_blood",
    -- "page28/cambion_conception",
    -- "page28/immaculate_conception",
    -- "page28/more_options",
    -- "page28/crown_of_light",
    -- "page28/deep_pockets",
    -- "page28/succubus",
    -- "page28/fruit_cake",
    -- "page28/teleport_2",
    -- "page28/black_powder",
    -- "page28/kidney_bean",
    -- "page28/glowing_hour_glass",
    -- "page28/circle_of_protection",
    -- "page28/sack_head",
    -- "page28/night_light",

    -- Page 29
    -- "page29/obsessed_fan",
    -- "page29/mine_crafter",
    -- "page29/pjs",
    "page29/head_of_the_keeper",
    -- "page29/papa_fly",
    -- "page29/multidimensional_baby",
    -- "page29/glitter_bombs",
    -- "page29/my_shadow",
    -- "page29/jar_of_flies",
    -- "page29/lil_loki",
    -- "page29/milk",
    -- "page29/d7",
    -- "page29/binky",
    -- "page29/moms_box",
    -- "page29/kidney_stone",

    -- Page 30
    -- "page30/mega_blast",
    -- "page30/dark_princes_crown",
    -- "page30/apple",
    -- "page30/lead_pencil",
    -- "page30/dog_tooth",
    -- "page30/dead_tooth",
    -- "page30/linger_bean",
    -- "page30/shard_of_glass",
    -- "page30/metal_plate",
    -- "page30/eye_of_greed",
    -- "page30/tarot_cloth",
    -- "page30/vericose_veins",
    -- "page30/compound_fracture",
    -- "page30/polydactyly",
    -- "page30/dads_lost_coin",

    -- Page 31
    "page31/midnight_snack",
    -- "page31/cone_head",
    -- "page31/belly_button",
    -- "page31/sinus_infection",
    -- "page31/glaucoma",
    -- "page31/parasitoid",
    -- "page31/eye_of_belial",
    -- "page31/sulfuric_acid",
    -- "page31/glyph_of_balance",
    -- "page31/analog_stick",
    -- "page31/contagion",
    -- "page31/finger",
    -- "page31/shade",
    -- "page31/depression",
    -- "page31/hushy",

    -- Page 32
    -- "page32/lil_monstro",
    -- "page32/king_baby",
    -- "page32/big_chubby",
    -- "page32/plan_c",
    -- "page32/d1",
    -- "page32/void",
    -- "page32/pause",
    -- "page32/smelter",
    -- "page32/compost",
    -- "page32/dataminer",
    -- "page32/clicker",
    -- "page32/mama_mega",
    -- "page32/wait_what",
    -- "page32/crooked_penny",
    -- "page32/dull_razor",

    -- Page 33
    -- "page33/potato_peeler",
    -- "page33/metronome",
    -- "page33/d_infinity",
    -- "page33/edens_soul",
    -- "page33/acid_baby",
    -- "page33/yo_listen",
    -- "page33/adrenaline",
    -- "page33/jacobs_ladder",
    -- "page33/ghost_pepper",
    -- "page33/euthanasia",
    -- "page33/camo_undies",
    -- "page33/duality",
    -- "page33/eucharist",
    -- "page33/sack_of_sacks",
    "page33/greeds_gullet",

    -- Page 34
    -- "page34/large_zit",
    -- "page34/little_horn",
    -- "page34/brown_nugget",
    -- "page34/poke_go",
    -- "page34/backstabber",
    -- "page34/sharp_straw",
    -- "page34/moms_razor",
    -- "page34/bloodshot_eye",
    -- "page34/delirious",
    -- "page34/angry_fly",
    -- "page34/black_hole",
    -- "page34/bozo",
    -- "page34/broken_modem",
    -- "page34/mystery_gift",
    -- "page34/sprinkler",

    -- Page 35
    -- "page35/fast_bombs",
    -- "page35/buddy_in_a_box",
    -- "page35/lil_delirium",
    -- "page35/jumper_cables",
    -- "page35/coupon",
    -- "page35/telekinesis",
    -- "page35/moving_box",
    -- "page35/technology_zero",
    -- "page35/leprosy",
    -- "page35/7_seals",
    -- "page35/mr_me",
    -- "page35/angelic_prism",
    -- "page35/pop",
    -- "page35/deaths_list",
    -- "page35/haemolacria",

    -- Page 36
    -- "page36/lacryphagy",
    -- "page36/trisagion",
    -- "page36/schoolbag",
    -- "page36/blanket",
    -- "page36/sacrificial_dagger",
    -- "page36/lil_spewer",
    -- "page36/marbles",
    -- "page36/mystery_bag",
    -- "page36/flat_stone",
    -- "page36/marrow",
    -- "page36/slipped_rib",
    -- "page36/hallowed_ground",
    -- "page36/pointy_rib",
    -- "page36/book_of_the_dead",
    -- "page36/dads_ring",

    -- Page 37
    -- "page37/divorce_papers",
    -- "page37/jaw_bone",
    -- "page37/brittle_bones",
    -- "page37/broken_shovel_handle",
    -- "page37/broken_shovel_head",
    -- "page37/moms_shovel",
    -- "page37/clear_rune",
    -- "page37/mucormycosis",
    -- "page37/2spooky",
    -- "page37/golden_razor",
    -- "page37/sulfur",
    -- "page37/fortune_cookie",
    -- "page37/eye_sore",
    -- "page37/120_volt",
    -- "page37/it_hurts",

    -- Page 38
    -- "page38/almond_milk",
    -- "page38/rock_bottom",
    -- "page38/nancy_bombs",
    -- "page38/bar_of_soap",
    -- "page38/blood_puppy",
    -- "page38/dream_catcher",
    -- "page38/pascal_candle",
    -- "page38/divine_intervention",
    -- "page38/blood_oath",
    -- "page38/playdough_cookie",
    -- "page38/orphan_socks",
    -- "page38/eye_of_the_occult",
    -- "page38/immaculate_heart",
    -- "page38/monstrance",
    -- "page38/the_intruder",

    -- Page 39
    -- "page39/dirty_mind",
    -- "page39/damocles",
    -- "page39/free_lemonade",
    -- "page39/spirit_sword",
    -- "page39/red_key",
    -- "page39/psy_fly",
    -- "page39/wavy_cap",
    -- "page39/rocket_in_a_jar",
    -- "page39/book_of_virtues",
    -- "page39/alabaster_box",
    -- "page39/the_stairway",
    "page39/sol",
    "page39/luna",
    "page39/mercurius",
    "page39/venus",

    -- Page 40
    "page40/terra",
    "page40/mars",
    "page40/jupiter",
    "page40/saturnus",
    "page40/uranus",
    "page40/neptunus",
    "page40/pluto",
    -- "page40/voodoo_head",
    -- "page40/eye_drops",
    -- "page40/act_of_contrition",
    -- "page40/member_card",
    -- "page40/battery_pack",
    -- "page40/moms_bracelet",
    -- "page40/the_scooper",
    -- "page40/ocular_rift",

    -- Page 41
    -- "page41/boiled_baby",
    -- "page41/freezer_baby",
    -- "page41/eternal_d6",
    -- "page41/bird_cage",
    -- "page41/larynx",
    -- "page41/lost_soul",
    -- "page41/blood_bombs",
    -- "page41/lil_dumpy",
    -- "page41/birds_eye",
    -- "page41/lodestone",
    -- "page41/rotten_tomato",
    -- "page41/birthright",
    -- "page41/red_stew",
    -- "page41/genesis",
    -- "page41/sharp_key",

    -- Page 42
    -- "page42/booster_pack",
    -- "page42/mega_mush",
    -- "page42/knife_piece_1",
    -- "page42/knife_piece_2",
    -- "page42/death_certificate",
    -- "page42/bot_fly",
    -- "page42/meat_cleaver",
    -- "page42/evil_charm",
    -- "page42/dogma",
    -- "page42/purgatory",
    -- "page42/stitches",
    -- "page42/r_key",
    -- "page42/knockout_drops",
    -- "page42/eraser",
    -- "page42/yuck_heart",

    -- Page 43
    -- "page43/urn_of_souls",
    -- "page43/akeldama",
    -- "page43/magic_skin",
    -- "page43/revelation",
    -- "page43/consolation_prize",
    -- "page43/tinytoma",
    -- "page43/brimstone_bombs",
    -- "page43/4_point_5_volt",
    -- "page43/fruity_plum",
    -- "page43/plum_flute",
    -- "page43/star_of_bethlehem",
    -- "page43/cube_baby",
    -- "page43/vade_retro",
    -- "page43/false_phd",
    -- "page43/spin_to_win",

    -- Page 44
    -- "page44/vasculitis",
    -- "page44/giant_cell",
    -- "page44/tropicamide",
    -- "page44/card_reading",
    -- "page44/quints",
    -- "page44/tooth_and_nail",
    "page44/binge_eater",
    -- "page44/guppys_eye",
    -- "page44/strawman",
    -- "page44/dads_note",
    -- "page44/sausage",
    -- "page44/options_question",
    -- "page44/candy_heart",
    -- "page44/a_pound_of_flesh",
    -- "page44/redemption",

    -- Page 45
    -- "page45/spirit_shackles",
    -- "page45/cracked_orb",
    -- "page45/empty_heart",
    -- "page45/astral_projection",
    -- "page45/c_section",
    -- "page45/lil_abaddon",
    -- "page45/montezumas_revenge",
    -- "page45/lil_portal",
    -- "page45/worm_friend",
    -- "page45/bone_spurs",
    -- "page45/hungry_soul",
    -- "page45/jar_of_wisps",
    -- "page45/soul_locket",
    -- "page45/friend_finder",
    -- "page45/inner_child",

    -- Page 46
    -- "page46/glitched_crown",
    -- "page46/belly_jelly",
    -- "page46/sacred_orb",
    -- "page46/sanguine_bond",
    -- "page46/the_swarm",
    -- "page46/heartbreak",
    -- "page46/bloody_gust",
    -- "page46/salvation",
    -- "page46/vanishing_twin",
    -- "page46/twisted_pair",
    -- "page46/azazels_rage",
    -- "page46/echo_chamber",
    -- "page46/isaacs_tomb",
    -- "page46/vengeful_spirit",
    -- "page46/esau_jr",

    -- Page 47
    -- "page47/berserk",
    -- "page47/dark_arts",
    -- "page47/abyss",
    -- "page47/supper",
    -- "page47/stapler",
    -- "page47/suplex",
    -- "page47/bag_of_crafting",
    -- "page47/flip",
    -- "page47/lemegeton",
    -- "page47/sumptorium",
    -- "page47/recall",
    -- "page47/hold",
    -- "page47/keepers_sack",
    -- "page47/keepers_kin",
    -- "page47/keepers_box",

    -- Page 48
    -- "page48/everything_jar",
    -- "page48/tm_trainer",
    -- "page48/anima_sola",
    -- "page48/spindown_dice",
    -- "page48/hypercoagulation",
    -- "page48/ibs",
    -- "page48/hemoptysis",
    -- "page48/ghost_bombs",
    -- "page48/gello",
    -- "page48/decap_attack",
    -- "page48/glass_eye",
    -- "page48/stye",
    -- "page48/moms_ring",
}

BI.ENABLED_BOOSTERS = {
    "treasure_room",
    -- "boss"
    -- "secret_room",
    -- "devil_room",
    -- "angel_room",

    -- "dice_room",
    -- "bedroom",
    -- "vault",
    -- "arcade",
    -- "planetarium",
}

BI.POOLS = {
    VANILLA_Common = {
        "j_joker",
        "j_greedy_joker",
        "j_lusty_joker",
        "j_wrathful_joker",
        "j_gluttenous_joker",
        "j_jolly",
        "j_zany",
        "j_mad",
        "j_crazy",
        "j_droll",
        "j_sly",
        "j_wily",
        "j_clever",
        "j_devious",
        "j_crafty",
        "j_half",
        "j_credit_card",
        "j_banner",
        "j_mystic_summit",
        "j_8_ball",
        "j_misprint",
        "j_raised_rist",
        "j_chaos",
        "j_egg",
        "j_runner",
        "j_ice_cream",
        "j_splash",
        "j_blue_joker",
        "j_faceless",
        "j_green_joker",
        "j_superposition",
        "j_todo_list",
        "j_cavendish",
        "j_red_card",
        "j_square",
        "j_riff_raff",
        "j_photograph",
        "j_reserved_parking",
        "j_mail",
        "j_hallucination",
        "j_fortune_teller",
        "j_juggler",
        "j_drunkard",
        "j_golden",
        "j_popcorn",
        "j_walkie_talkie",
        "j_smiley",
        "j_ticket",
        "j_swashbuckler",
        "j_hanging_chad",
        "j_shoot_the_moon"
    },
    VANILLA_Uncommon = {
        "j_stencil",
        "j_four_fingers",
        "j_mime",
        "j_ceremonial",
        "j_marble",
        "j_loyalty_card",
        "j_dusk",
        "j_fibonacci",
        "j_steel_joker",
        "j_hack",
        "j_pareidolia",
        "j_space",
        "j_burglar",
        "j_blackboard",
        "j_sixth_sense",
        "j_constellation",
        "j_hiker",
        "j_card_sharp",
        "j_seance",
        "j_vampire",
        "j_shortcut",
        "j_hologram",
        "j_cloud_9",
        "j_rocket",
        "j_midas_mask",
        "j_luchador",
        "j_gift_card",
        "j_turtle_bean",
        "j_erosion",
        "j_to_the_moon",
        "j_stone",
        "j_lucky_cat",
        "j_bull",
        "j_diet_cola",
        "j_trading",
        "j_flash",
        "j_trousers",
        "j_ramen",
        "j_selzer",
        "j_castle",
        "j_mr_bones",
        "j_acrobat",
        "j_sock_and_buskin",
        "j_troubadour",
        "j_certificate",
        "j_smeared",
        "j_throwback",
        "j_rough_gem",
        "j_bloodstone",
        "j_arrowhead",
        "j_onyx_agate",
        "j_glass",
        "j_ring_master",
        "j_flower_pot",
        "j_merry_andy",
        "j_oops",
        "j_idol",
        "j_seeing_double",
        "j_matador",
        "j_satellite",
        "j_cartomancer",
        "j_astronomer",
        "j_boostraps"
    },
    VANILLA_Rare = {
        "j_dna",
        "j_vagabond",
        "j_baron",
        "j_baseball",
        "j_ancient",
        "j_campfire",
        "j_blueprint",
        "j_wee",
        "j_hit_the_road",
        "j_duo",
        "j_trio",
        "j_family",
        "j_order",
        "j_tribe",
        "j_stuntman",
        "j_invisible",
        "j_brainstorm",
        "j_drivers_license",
        "j_burnt"
    },
    VANILLA_Legendary = {
        "j_caino",
        "j_triboulet",
        "j_yorick",
        "j_chicot",
        "j_perkeo"
    },

    TBOI_Treasure = {
        "j_tboi_sad_onion",
        "j_tboi_inner_eye",
        "j_tboi_spoon_bender",
        "j_tboi_crickets_head",
        "j_tboi_my_reflection",
        "j_tboi_number_one",
        "j_tboi_blood_of_the_martyr",
        "j_tboi_brother_bobby",
        "j_tboi_halo_of_flies",
        "j_tboi_magic_mushroom",
        "j_tboi_the_virus",
        "j_tboi_roid_rage",
        "j_tboi_less_than_3",
        "j_tboi_skeleton_key",
        "j_tboi_boom",
        "j_tboi_the_d6",
        "j_tboi_midas_touch",
        "j_tboi_d4",
    },
    TBOI_Shop = {
        "j_tboi_the_compass",
        "j_tboi_head_of_the_keeper",
    },
    TBOI_Boss = {
        "j_tboi_roid_rage",
        "j_tboi_lunch",
        "j_tboi_dinner",
        "j_tboi_dessert",
        "j_tboi_breakfast",
        "j_tboi_rotten_meat",
        "j_tboi_wooden_spoon",
        "j_tboi_the_belt",
        "j_tboi_moms_underwear",
        "j_tboi_moms_heels",
        "j_tboi_midnight_snack",
    },
    TBOI_Secret = {
        "j_tboi_1up",
        "j_tboi_raw_liver",
        "j_tboi_skeleton_key",
        "j_tboi_transcendence",
        "j_tboi_greeds_gullet",
        "j_tboi_binge_eater",
    },
    TBOI_Devil = {
        "j_tboi_brother_bobby",
        "j_tboi_empty_vessel",
    },
    TBOI_Angel = {
        "j_tboi_blood_of_the_martyr"
    },
    TBOI_Arcade = {
        "j_tboi_skatole",
        "j_tboi_a_dollar",
    },
    TBOI_Planetarium = {
        "j_tboi_sol",
        "j_tboi_luna",
        "j_tboi_mercurius",
        "j_tboi_venus",
        "j_tboi_terra",
        "j_tboi_mars",
        "j_tboi_jupiter",
        "j_tboi_saturnus",
        "j_tboi_uranus",
        "j_tboi_neptunus",
        "j_tboi_pluto"
    },
    TBOI_Chaos = {
        "j_tboi_sad_onion",
        "j_tboi_inner_eye",
        "j_tboi_spoon_bender",
        "j_tboi_crickets_head",
        "j_tboi_my_reflection",
        "j_tboi_number_one",
        "j_tboi_blood_of_the_martyr",
        "j_tboi_brother_bobby",
        "j_tboi_skatole",
        "j_tboi_halo_of_flies",
        "j_tboi_1up",
        "j_tboi_magic_mushroom",
        "j_tboi_the_virus",
        "j_tboi_roid_rage",
        "j_tboi_less_than_3",
        "j_tboi_raw_liver",
        --"j_tboi_skeleton_key", -- Keys still unimplemented
        "j_tboi_a_dollar",
        --"j_tboi_boom", -- Bombs still unimplemented
        "j_tboi_transcendence",
        "j_tboi_the_compass",
        "j_tboi_lunch",
        "j_tboi_dinner",
        "j_tboi_dessert",
        "j_tboi_breakfast",
        "j_tboi_rotten_meat",
        "j_tboi_wooden_spoon",
        "j_tboi_the_belt",
        "j_tboi_moms_underwear",
        "j_tboi_moms_heels",
        -- "j_tboi_moms_lipstick",
        -- "j_tboi_wire_coat_hanger",
        -- "j_tboi_the_bible",
        -- "j_tboi_the_book_of_belial",
        -- "j_tboi_the_necronomicon",
        -- "j_tboi_the_poop",
        -- "j_tboi_mr_boom",
        -- "j_tboi_tammys_head",
        -- "j_tboi_moms_bra",
        -- "j_tboi_kamikaze",
        -- "j_tboi_moms_pad",
        -- "j_tboi_bobs_rotten_head",
        -- "j_tboi_teleport",
        -- "j_tboi_yum_heart",
        -- "j_tboi_lucky_foot",
        -- "j_tboi_doctors_remote",
        -- "j_tboi_cupids_arrow",
        -- "j_tboi_shoop_da_woop",
        -- "j_tboi_steven",
        -- "j_tboi_pentagram",
        -- "j_tboi_dr_fetus",
        -- "j_tboi_magneto",
        -- "j_tboi_treasure_map",
        -- "j_tboi_moms_eye",
        -- "j_tboi_lemon_mishap",
        -- "j_tboi_distant_admiration",
        -- "j_tboi_book_of_shadows",
        -- "j_tboi_the_ladder",
        -- "j_tboi_charm_of_the_vampire",
        -- "j_tboi_the_battery",
        -- "j_tboi_steam_sale",
        -- "j_tboi_anarchist_cookbook",
        -- "j_tboi_the_hourglass",
        -- "j_tboi_sister_maggy",
        -- "j_tboi_technology",
        -- "j_tboi_chocolate_milk",
        -- "j_tboi_growth_hormones",
        -- "j_tboi_mini_mush",
        -- "j_tboi_rosary",
        -- "j_tboi_cube_of_meat",
        -- "j_tboi_a_quarter",
        -- "j_tboi_phd",
        -- "j_tboi_xray_vision",
        -- "j_tboi_my_little_unicorn",
        -- "j_tboi_book_of_revelations",
        -- "j_tboi_the_mark",
        -- "j_the_pact",
        -- "j_tboi_dead_cat",
        -- "j_tboi_lord_of_the_pit",
        -- "j_tboi_the_nail",
        -- "j_tboi_we_need_to_go_deeper",
        -- "j_tboi_deck_of_cards",
        -- "j_tboi_monstros_tooth",
        -- "j_tboi_lokis_horns",
        -- "j_tboi_little_chubby",
        -- "j_tboi_spider_bite",
        -- "j_tboi_the_small_rock",
        -- "j_tboi_spelunker_hat",
        -- "j_tboi_super_bandage",
        -- "j_tboi_the_gamekid",
        -- "j_tboi_sack_of_pennies",
        -- "j_tboi_robo_baby",
        -- "j_tboi_little_chad",
        -- "j_tboi_the_book_of_sin",
        -- "j_tboi_the_relic",
        -- "j_tboi_little_gish",
        -- "j_tboi_little_steven",
        -- "j_tboi_the_halo",
        -- "j_tboi_moms_bottle_of_pills",
        -- "j_tboi_the_common_cold",
        -- "j_tboi_the_parasite",
        "j_tboi_the_d6",
        -- "j_tboi_mr_mega",
        -- "j_tboi_pinking_shears",
        -- "j_tboi_the_wafer",
        -- "j_tboi_money_equals_power",
        -- "j_tboi_moms_contacts",
        -- "j_tboi_the_bean",
        -- "j_tboi_guardian_angel",
        -- "j_tboi_demon_baby",
        -- "j_tboi_moms_knife",
        -- "j_tboi_ouija_board",
        -- "j_tboi_9_volt",
        -- "j_tboi_dead_bird",
        -- "j_tboi_brimstone",
        -- "j_tboi_blood_bag",
        -- "j_tboi_skinny_odd_mushroom",
        -- "j_tboi_fat_odd_mushroom",
        -- "j_tboi_whore_of_babylon",
        -- "j_tboi_monster_manual",
        -- "j_tboi_dead_sea_scrolls",
        -- "j_tboi_bobby_bomb",
        -- "j_tboi_razor_blade",
        -- "j_tboi_forget_me_now",
        -- "j_tboi_forever_alone",
        -- "j_tboi_bucket_of_lard",
        -- "j_tboi_a_pony",
        -- "j_tboi_bomb_bag",
        -- "j_tboi_a_lump_of_coal",
        -- "j_tboi_guppys_paw",
        -- "j_tboi_guppys_tail",
        -- "j_tboi_iv_bag",
        -- "j_tboi_best_friend",
        -- "j_tboi_remote_detonator",
        -- "j_tboi_stigmata",
        -- "j_tboi_moms_purse",
        -- "j_tboi_bobs_curse",
        -- "j_tboi_pageant_boy",
        -- "j_tboi_scapular",
        -- "j_tboi_speed_ball",
        -- "j_tboi_bum_friend",
        -- "j_tboi_guppys_head",
        -- "j_tboi_prayer_card",
        -- "j_tboi_notched_axe",
        -- "j_tboi_infestation",
        -- "j_tboi_ipecac",
        -- "j_tboi_tough_love",
        -- "j_tboi_the_mulligan",
        -- "j_tboi_technology_2",
        -- "j_tboi_mutant_spider",
        -- "j_tboi_chemical_peel",
        -- "j_tboi_the_peeper",
        -- "j_tboi_habit",
        -- "j_tboi_bloody_lust",
        -- "j_tboi_crystal_ball",
        -- "j_tboi_spirit_of_the_night",
        -- "j_tboi_crack_the_sky",
        -- "j_tboi_ankh",
        -- "j_tboi_celtic_cross",
        -- "j_tboi_ghost_baby",
        -- "j_tboi_the_candle",
        -- "j_tboi_cat_o_nine_tails",
        -- "j_tboi_d20",
        -- "j_tboi_harlequin_baby",
        -- "j_tboi_epic_fetus",
        -- "j_tboi_polyphemus",
        -- "j_tboi_daddy_longlegs",
        -- "j_tboi_spider_butt",
        -- "j_tboi_sacrificial_dagger",
        -- "j_tboi_mitre",
        -- "j_tboi_rainbow_baby",
        -- "j_tboi_dads_key",
        -- "j_tboi_stem_cells",
        -- "j_tboi_portable_slot",
        -- "j_tboi_holy_water",
        -- "j_tboi_fate",
        -- "j_tboi_the_black_bean",
        -- "j_tboi_white_pony",
        -- "j_tboi_sacred_heart",
        -- "j_tboi_toothpicks",
        -- "j_tboi_holy_grail",
        -- "j_tboi_dead_dove",
        -- "j_tboi_blood_rights",
        -- "j_tboi_guppys_hairball",
        -- "j_tboi_abel",
        -- "j_tboi_smb_super_fan",
        -- "j_tboi_pyro",
        -- "j_tboi_3_dollar_bill",
        -- "j_tboi_telepathy_for_dummies",
        -- "j_tboi_meat",
        -- "j_tboi_magic_8_ball",
        -- "j_tboi_moms_coin_purse",
        -- "j_tboi_squeezy",
        -- "j_tboi_jesus_juice",
        -- "j_tboi_box",
        -- "j_tboi_moms_key",
        -- "j_tboi_moms_eyeshadow",
        -- "j_tboi_iron_bar",
        "j_tboi_midas_touch",
        -- "j_tboi_humbleing_bundle",
        -- "j_tboi_fanny_pack",
        -- "j_tboi_sharp_plug",
        -- "j_tboi_the_guillotine",
        -- "j_tboi_ball_of_bandages",
        -- "j_tboi_champion_belt",
        -- "j_tboi_butt_bombs",
        -- "j_tboi_gnawed_leaf",
        -- "j_tboi_spiderbaby",
        -- "j_tboi_guppys_collar",
        -- "j_tboi_lost_contact",
        -- "j_tboi_anemic",
        -- "j_tboi_goat_head",
        -- "j_tboi_ceremonial_robes",
        -- "j_tboi_moms_wig",
        -- "j_tboi_placenta",
        -- "j_tboi_old_bandage",
        -- "j_tboi_sad_bombs",
        -- "j_tboi_rubber_cement",
        -- "j_tboi_anti_gravity",
        -- "j_tboi_pyromaniac",
        -- "j_tboi_crickets_body",
        -- "j_tboi_gimpy",
        -- "j_tboi_black_lotus",
        -- "j_tboi_piggy_bank",
        -- "j_tboi_moms_perfume",
        -- "j_tboi_monstros_lung",
        -- "j_tboi_abaddon",
        -- "j_tboi_ball_of_tar",
        -- "j_tboi_stop_watch",
        -- "j_tboi_tiny_planet",
        -- "j_tboi_infestation_2",
        -- "j_tboi_e_coli",
        -- "j_tboi_deaths_touch",
        -- "j_tboi_key_piece_1",
        -- "j_tboi_key_piece_2",
        -- "j_tboi_experimental_treatment",
        -- "j_tboi_contract_from_below",
        -- "j_tboi_infamy",
        -- "j_tboi_trinity_shield",
        -- "j_tboi_tech_point_5",
        -- "j_tboi_20_20",
        -- "j_tboi_blue_map",
        -- "j_tboi_bffs",
        -- "j_tboi_hive_mind",
        -- "j_tboi_theres_options",
        -- "j_tboi_bogo_bombs",
        -- "j_tboi_starter_deck",
        -- "j_tboi_little_baggy",
        -- "j_tboi_magic_scab",
        -- "j_tboi_blood_clot",
        -- "j_tboi_screw",
        -- "j_tboi_hot_bombs",
        -- "j_tboi_fire_mind",
        -- "j_tboi_missing_no",
        -- "j_tboi_dark_matter",
        -- "j_tboi_black_candle",
        -- "j_tboi_proptosis",
        -- "j_tboi_missing_page_2",
        -- "j_tboi_smart_fly",
        -- "j_tboi_dry_baby",
        -- "j_tboi_juicy_sack",
        -- "j_tboi_robo_baby_2",
        -- "j_tboi_rotten_baby",
        -- "j_tboi_headless_baby",
        -- "j_tboi_leech",
        -- "j_tboi_mystery_sack",
        -- "j_tboi_bbf",
        -- "j_tboi_bobs_brain",
        -- "j_tboi_best_bud",
        -- "j_tboi_lil_brimstone",
        -- "j_tboi_isaacs_heart",
        -- "j_tboi_lil_haunt",
        -- "j_tboi_dark_bum",
        -- "j_tboi_big_fan",
        -- "j_tboi_sissy_long_legs",
        -- "j_tboi_punching_bag",
        -- "j_tboi_how_to_jump",
        -- "j_tboi_d100",
        "j_tboi_d4",
        -- "j_tboi_d10",
        -- "j_tboi_blank_card",
        -- "j_tboi_book_of_secrets",
        -- "j_tboi_box_of_spiders",
        -- "j_tboi_red_candle",
        -- "j_tboi_the_jar",
        -- "j_tboi_flush",
        -- "j_tboi_satanic_bible",
        -- "j_tboi_head_of_krampus",
        -- "j_tboi_butter_bean",
        -- "j_tboi_magic_fingers",
        -- "j_tboi_converter",
        -- "j_tboi_pandoras_box",
        -- "j_tboi_unicorn_stump",
        -- "j_tboi_taurus",
        -- "j_tboi_aries",
        -- "j_tboi_cancer",
        -- "j_tboi_leo",
        -- "j_tboi_virgo",
        -- "j_tboi_libra",
        -- "j_tboi_scorpio",
        -- "j_tboi_sagittarius",
        -- "j_tboi_capricorn",
        -- "j_tboi_aquarius",
        -- "j_tboi_pisces",
        -- "j_tboi_eves_mascara",
        -- "j_tboi_judas_shadow",
        -- "j_tboi_maggys_bow",
        -- "j_tboi_holy_mantle",
        -- "j_tboi_thunder_thighs",
        -- "j_tboi_strange_attractor",
        -- "j_tboi_cursed_eye",
        -- "j_tboi_mysterious_liquid",
        -- "j_tboi_gemini",
        -- "j_tboi_cains_other_eye",
        -- "j_tboi_blue_babys_only_friend",
        -- "j_tboi_samsons_chains",
        -- "j_tboi_mongo_baby",
        -- "j_tboi_isaacs_tears",
        -- "j_tboi_undefined",
        -- "j_tboi_scissors",
        -- "j_tboi_breath_of_life",
        -- "j_tboi_the_polaroid",
        -- "j_tboi_the_negative",
        -- "j_tboi_the_ludovico_technique",
        -- "j_tboi_soy_milk",
        -- "j_tboi_godhead",
        -- "j_tboi_lazarus_rags",
        -- "j_tboi_the_mind",
        -- "j_tboi_the_body",
        -- "j_tboi_the_soul",
        -- "j_tboi_dead_onion",
        -- "j_tboi_broken_watch",
        -- "j_tboi_boomerang",
        -- "j_tboi_safety_pin",
        -- "j_tboi_caffeine_pill",
        -- "j_tboi_torn_photo",
        -- "j_tboi_blue_cap",
        -- "j_tboi_latch_key",
        -- "j_tboi_match_book",
        -- "j_tboi_synthoil",
        -- "j_tboi_a_snack",
        -- "j_tboi_diplopia",
        -- "j_tboi_placebo",
        -- "j_tboi_wooden_nickel",
        -- "j_tboi_toxic_shock",
        -- "j_tboi_mega_bean",
        -- "j_tboi_glass_cannon",
        -- "j_tboi_bomber_boy",
        -- "j_tboi_crack_jacks",
        -- "j_tboi_moms_pearls",
        -- "j_tboi_car_battery",
        -- "j_tboi_box_of_friends",
        -- "j_tboi_the_wiz",
        -- "j_tboi_8_inch_nails",
        -- "j_tboi_incubus",
        -- "j_tboi_fates_reward",
        -- "j_tboi_lil_chest",
        -- "j_tboi_sworn_protector",
        -- "j_tboi_friend_zone",
        -- "j_tboi_lost_fly",
        -- "j_tboi_scatter_bombs",
        -- "j_tboi_sticky_bombs",
        -- "j_tboi_epiphora",
        -- "j_tboi_continuum",
        -- "j_tboi_mr_dolly",
        -- "j_tboi_curse_of_the_tower",
        -- "j_tboi_charged_baby",
        -- "j_tboi_dead_eye",
        -- "j_tboi_holy_light",
        -- "j_tboi_host_hat",
        -- "j_tboi_restock",
        -- "j_tboi_bursting_sack",
        -- "j_tboi_no_2",
        -- "j_tboi_pupula_duplex",
        -- "j_tboi_pay_to_play",
        -- "j_tboi_edens_blessing",
        -- "j_tboi_friendly_ball",
        -- "j_tboi_tear_detonator",
        -- "j_tboi_lil_gurdy",
        -- "j_tboi_bumbo",
        -- "j_tboi_d12",
        -- "j_tboi_censer",
        -- "j_tboi_key_bum",
        -- "j_tboi_rune_bag",
        -- "j_tboi_seraphim",
        -- "j_tboi_betrayal",
        -- "j_tboi_zodiac",
        -- "j_tboi_serpents_kiss",
        -- "j_tboi_marked",
        -- "j_tboi_tech_x",
        -- "j_tboi_ventricle_razor",
        -- "j_tboi_tractor_beam",
        -- "j_tboi_gods_flesh",
        -- "j_tboi_maw_of_the_void",
        -- "j_tboi_spear_of_destiny",
        -- "j_tboi_explosivo",
        -- "j_tboi_chaos",
        -- "j_tboi_spider_mod",
        -- "j_tboi_farting_baby",
        -- "j_tboi_gb_bug",
        -- "j_tboi_d8",
        -- "j_tboi_purity",
        -- "j_tboi_athame",
        "j_tboi_empty_vessel",
        -- "j_tboi_evil_eye",
        -- "j_tboi_lusty_blood",
        -- "j_tboi_cambion_conception",
        -- "j_tboi_immaculate_conception",
        -- "j_tboi_more_options",
        -- "j_tboi_crown_of_light",
        -- "j_tboi_deep_pockets",
        -- "j_tboi_succubus",
        -- "j_tboi_fruit_cake",
        -- "j_tboi_teleport_2",
        -- "j_tboi_black_powder",
        -- "j_tboi_kidney_bean",
        -- "j_tboi_glowing_hour_glass",
        -- "j_tboi_circle_of_protection",
        -- "j_tboi_sack_head",
        -- "j_tboi_night_light",
        -- "j_tboi_obsessed_fan",
        -- "j_tboi_mine_crafter",
        -- "j_tboi_pjs",
        "j_tboi_head_of_the_keeper",
        -- "j_tboi_papa_fly",
        -- "j_tboi_multidimensional_baby",
        -- "j_tboi_glitter_bombs",
        -- "j_tboi_my_shadow",
        -- "j_tboi_jar_of_flies",
        -- "j_tboi_lil_loki",
        -- "j_tboi_milk",
        -- "j_tboi_d7",
        -- "j_tboi_binky",
        -- "j_tboi_moms_box",
        -- "j_tboi_kidney_stone",
        -- "j_tboi_mega_blast",
        -- "j_tboi_dark_princes_crown",
        -- "j_tboi_apple",
        -- "j_tboi_lead_pencil",
        -- "j_tboi_dog_tooth",
        -- "j_tboi_dead_tooth",
        -- "j_tboi_linger_bean",
        -- "j_tboi_shard_of_glass",
        -- "j_tboi_metal_plate",
        -- "j_tboi_eye_of_greed",
        -- "j_tboi_tarot_cloth",
        -- "j_tboi_vericose_veins",
        -- "j_tboi_compound_fracture",
        -- "j_tboi_polydactyly",
        -- "j_tboi_dads_lost_coin",
        "j_tboi_midnight_snack",
        -- "j_tboi_cone_head",
        -- "j_tboi_belly_button",
        -- "j_tboi_sinus_infection",
        -- "j_tboi_glaucoma",
        -- "j_tboi_parasitoid",
        -- "j_tboi_eye_of_belial",
        -- "j_tboi_sulfuric_acid",
        -- "j_tboi_glyph_of_balance",
        -- "j_tboi_analog_stick",
        -- "j_tboi_contagion",
        -- "j_tboi_finger",
        -- "j_tboi_shade",
        -- "j_tboi_depression",
        -- "j_tboi_hushy",
        -- "j_tboi_lil_monstro",
        -- "j_tboi_king_baby",
        -- "j_tboi_big_chubby",
        -- "j_tboi_plan_c",
        -- "j_tboi_d1",
        -- "j_tboi_void",
        -- "j_tboi_pause",
        -- "j_tboi_smelter",
        -- "j_tboi_compost",
        -- "j_tboi_dataminer",
        -- "j_tboi_clicker",
        -- "j_tboi_mama_mega",
        -- "j_tboi_wait_what",
        -- "j_tboi_crooked_penny",
        -- "j_tboi_dull_razor",
        -- "j_tboi_potato_peeler",
        -- "j_tboi_metronome",
        -- "j_tboi_d_infinity",
        -- "j_tboi_edens_soul",
        -- "j_tboi_acid_baby",
        -- "j_tboi_yo_listen",
        -- "j_tboi_adrenaline",
        -- "j_tboi_jacobs_ladder",
        -- "j_tboi_ghost_pepper",
        -- "j_tboi_euthanasia",
        -- "j_tboi_camo_undies",
        -- "j_tboi_duality",
        -- "j_tboi_eucharist",
        -- "j_tboi_sack_of_sacks",
        "j_tboi_greeds_gullet",
        -- "j_tboi_large_zit",
        -- "j_tboi_little_horn",
        -- "j_tboi_brown_nugget",
        -- "j_tboi_poke_go",
        -- "j_tboi_backstabber",
        -- "j_tboi_sharp_straw",
        -- "j_tboi_moms_razor",
        -- "j_tboi_bloodshot_eye",
        -- "j_tboi_delirious",
        -- "j_tboi_angry_fly",
        -- "j_tboi_black_hole",
        -- "j_tboi_bozo",
        -- "j_tboi_broken_modem",
        -- "j_tboi_mystery_gift",
        -- "j_tboi_sprinkler",
        -- "j_tboi_fast_bombs",
        -- "j_tboi_buddy_in_a_box",
        -- "j_tboi_lil_delirium",
        -- "j_tboi_jumper_cables",
        -- "j_tboi_coupon",
        -- "j_tboi_telekinesis",
        -- "j_tboi_moving_box",
        -- "j_tboi_technology_zero",
        -- "j_tboi_leprosy",
        -- "j_tboi_7_seals",
        -- "j_tboi_mr_me",
        -- "j_tboi_angelic_prism",
        -- "j_tboi_pop",
        -- "j_tboi_deaths_list",
        -- "j_tboi_haemolacria",
        -- "j_tboi_lacryphagy",
        -- "j_tboi_trisagion",
        -- "j_tboi_schoolbag",
        -- "j_tboi_blanket",
        -- "j_tboi_sacrificial_dagger",
        -- "j_tboi_lil_spewer",
        -- "j_tboi_marbles",
        -- "j_tboi_mystery_bag",
        -- "j_tboi_flat_stone",
        -- "j_tboi_marrow",
        -- "j_tboi_slipped_rib",
        -- "j_tboi_hallowed_ground",
        -- "j_tboi_pointy_rib",
        -- "j_tboi_book_of_the_dead",
        -- "j_tboi_dads_ring",
        -- "j_tboi_divorce_papers",
        -- "j_tboi_jaw_bone",
        -- "j_tboi_brittle_bones",
        -- "j_tboi_broken_shovel_handle",
        -- "j_tboi_broken_shovel_head",
        -- "j_tboi_moms_shovel",
        -- "j_tboi_clear_rune",
        -- "j_tboi_mucormycosis",
        -- "j_tboi_2spooky",
        -- "j_tboi_golden_razor",
        -- "j_tboi_sulfur",
        -- "j_tboi_fortune_cookie",
        -- "j_tboi_eye_sore",
        -- "j_tboi_120_volt",
        -- "j_tboi_it_hurts",
        -- "j_tboi_almond_milk",
        -- "j_tboi_rock_bottom",
        -- "j_tboi_nancy_bombs",
        -- "j_tboi_bar_of_soap",
        -- "j_tboi_blood_puppy",
        -- "j_tboi_dream_catcher",
        -- "j_tboi_pascal_candle",
        -- "j_tboi_divine_intervention",
        -- "j_tboi_blood_oath",
        -- "j_tboi_playdough_cookie",
        -- "j_tboi_orphan_socks",
        -- "j_tboi_eye_of_the_occult",
        -- "j_tboi_immaculate_heart",
        -- "j_tboi_monstrance",
        -- "j_tboi_the_intruder",
        -- "j_tboi_dirty_mind",
        -- "j_tboi_damocles",
        -- "j_tboi_free_lemonade",
        -- "j_tboi_spirit_sword",
        -- "j_tboi_red_key",
        -- "j_tboi_psy_fly",
        -- "j_tboi_wavy_cap",
        -- "j_tboi_rocket_in_a_jar",
        -- "j_tboi_book_of_virtues",
        -- "j_tboi_alabaster_box",
        -- "j_tboi_the_stairway",
        "j_tboi_sol",
        "j_tboi_luna",
        "j_tboi_mercurius",
        "j_tboi_venus",
        "j_tboi_terra",
        "j_tboi_mars",
        "j_tboi_jupiter",
        "j_tboi_saturnus",
        "j_tboi_uranus",
        "j_tboi_neptunus",
        "j_tboi_pluto",
        -- "j_tboi_voodoo_head",
        -- "j_tboi_eye_drops",
        -- "j_tboi_act_of_contrition",
        -- "j_tboi_member_card",
        -- "j_tboi_battery_pack",
        -- "j_tboi_moms_bracelet",
        -- "j_tboi_the_scooper",
        -- "j_tboi_ocular_rift",
        -- "j_tboi_boiled_baby",
        -- "j_tboi_freezer_baby",
        -- "j_tboi_eternal_d6",
        -- "j_tboi_bird_cage",
        -- "j_tboi_larynx",
        -- "j_tboi_lost_soul",
        -- "j_tboi_blood_bombs",
        -- "j_tboi_lil_dumpy",
        -- "j_tboi_birds_eye",
        -- "j_tboi_lodestone",
        -- "j_tboi_rotten_tomato",
        -- "j_tboi_birthright",
        -- "j_tboi_red_stew",
        -- "j_tboi_genesis",
        -- "j_tboi_sharp_key",
        -- "j_tboi_booster_pack",
        -- "j_tboi_mega_mush",
        -- "j_tboi_knife_piece_1",
        -- "j_tboi_knife_piece_2",
        -- "j_tboi_death_certificate",
        -- "j_tboi_bot_fly",
        -- "j_tboi_meat_cleaver",
        -- "j_tboi_evil_charm",
        -- "j_tboi_dogma",
        -- "j_tboi_purgatory",
        -- "j_tboi_stitches",
        -- "j_tboi_r_key",
        -- "j_tboi_knockout_drops",
        -- "j_tboi_eraser",
        -- "j_tboi_yuck_heart",
        -- "j_tboi_/urn_of_souls",
        -- "j_tboi_akeldama",
        -- "j_tboi_magic_skin",
        -- "j_tboi_revelation",
        -- "j_tboi_consolation_prize",
        -- "j_tboi_tinytoma",
        -- "j_tboi_brimstone_bombs",
        -- "j_tboi_4_point_5_volt",
        -- "j_tboi_fruity_plum",
        -- "j_tboi_plum_flute",
        -- "j_tboi_star_of_bethlehem",
        -- "j_tboi_cube_baby",
        -- "j_tboi_vade_retro",
        -- "j_tboi_false_phd",
        -- "j_tboi_spin_to_win",
        -- "j_tboi_vasculitis",
        -- "j_tboi_giant_cell",
        -- "j_tboi_tropicamide",
        -- "j_tboi_card_reading",
        -- "j_tboi_quints",
        -- "j_tboi_tooth_and_nail",
        "j_tboi_binge_eater",
        -- "j_tboi_guppys_eye",
        -- "j_tboi_strawman",
        -- "j_tboi_dads_note",
        -- "j_tboi_sausage",
        -- "j_tboi_options_question",
        -- "j_tboi_candy_heart",
        -- "j_tboi_a_pound_of_flesh",
        -- "j_tboi_redemption",
        -- "j_tboi_spirit_shackles",
        -- "j_tboi_cracked_orb",
        -- "j_tboi_empty_heart",
        -- "j_tboi_astral_projection",
        -- "j_tboi_c_section",
        -- "j_tboi_lil_abaddon",
        -- "j_tboi_montezumas_revenge",
        -- "j_tboi_lil_portal",
        -- "j_tboi_worm_friend",
        -- "j_tboi_bone_spurs",
        -- "j_tboi_hungry_soul",
        -- "j_tboi_jar_of_wisps",
        -- "j_tboi_soul_locket",
        -- "j_tboi_friend_finder",
        -- "j_tboi_inner_child",
        -- "j_tboi_glitched_crown",
        -- "j_tboi_belly_jelly",
        -- "j_tboi_sacred_orb",
        -- "j_tboi_sanguine_bond",
        -- "j_tboi_the_swarm",
        -- "j_tboi_heartbreak",
        -- "j_tboi_bloody_gust",
        -- "j_tboi_salvation",
        -- "j_tboi_vanishing_twin",
        -- "j_tboi_twisted_pair",
        -- "j_tboi_azazels_rage",
        -- "j_tboi_echo_chamber",
        -- "j_tboi_isaacs_tomb",
        -- "j_tboi_vengeful_spirit",
        -- "j_tboi_esau_jr",
        -- "j_tboi_berserk",
        -- "j_tboi_dark_arts",
        -- "j_tboi_abyss",
        -- "j_tboi_supper",
        -- "j_tboi_stapler",
        -- "j_tboi_suplex",
        -- "j_tboi_bag_of_crafting",
        -- "j_tboi_flip",
        -- "j_tboi_lemegeton",
        -- "j_tboi_sumptorium",
        -- "j_tboi_recall",
        -- "j_tboi_hold",
        -- "j_tboi_keepers_sack",
        -- "j_tboi_keepers_kin",
        -- "j_tboi_keepers_box",
        -- "j_tboi_everything_jar",
        -- "j_tboi_tm_trainer",
        -- "j_tboi_anima_sola",
        -- "j_tboi_spindown_dice",
        -- "j_tboi_hypercoagulation",
        -- "j_tboi_ibs",
        -- "j_tboi_hemoptysis",
        -- "j_tboi_ghost_bombs",
        -- "j_tboi_gello",
        -- "j_tboi_decap_attack",
        -- "j_tboi_glass_eye",
        -- "j_tboi_stye",
        -- "j_tboi_moms_ring",
    },
    C = {
        Treasure = HEX("F3E786"),
        Shop = HEX("D7B173"),
        Boss = HEX("C64845"),
        Secret = HEX("C2C5C7"),
        Devil = HEX("393D40"),
        Angel = HEX("C2D9ED"),
        Arcade = HEX("D1E3D2"),
        Planetarium = HEX("67CBD7"),
        Chaos = G.C.DARK_EDITION
    }
}

BI.ENABLED_CONSUMABLES = {
    TYPES = {
        "consumable_type"
    },
    ENABLED_REVERSED_TAROTS = {
        "r_fool",
        "r_magician",
        "r_high_priestess",
        "r_empress",
        "r_emperor",
        "r_hierophant",
        "r_lovers",
        "r_chariot",
        "r_justice",
        "r_hermit",
        "r_wheel_of_fortune",
        "r_strength",
        "r_hanged_man",
        "r_death",
        "r_temperance",
        "r_devil",
        "r_tower",
        "r_star",
        "r_moon",
        "r_sun",
        "r_judgement",
        "r_world"
    },
    ENABLED_RUNES = {
        "hagalaz",
        "jera",
        "ehwaz",
        "dagaz",
        "ansuz",
        "perthro",
        "berkano",
        "algiz",
        "blank_rune",
        "black_rune",
        "rune_shard"
    },
    ENABLED_SOUL_STONES = {
        "soul_of_isaac",
        "soul_of_magdalene",
        "soul_of_cain",
        "soul_of_judas",
        "soul_of_blue_baby",
        "soul_of_eve",
        "soul_of_samson",
        "soul_of_azazel",
        "soul_of_lazarus",
        "soul_of_eden",
        "soul_of_lost",
        "soul_of_lilith",
        "soul_of_keeper",
        "soul_of_apollyon",
        "soul_of_forgor",
        "soul_of_bethany",
        "soul_of_jacob_and_esau"
    }
}

BI.POISONOUS = {
    j_tboi_the_virus = true,
    j_tboi_bobs_rotten_head = true,
    j_tboi_the_common_cold = true,
    j_tboi_bobs_curse = true,
    j_tboi_bobs_brain = true,
    j_tboi_mysterious_liquid = true,
    j_tboi_toxic_shock = true,
    j_tboi_serpents_kiss = true,
    j_tboi_sinus_infection = true,
    j_tboi_contagion = true,
    j_tboi_mucormycosis = true,
    j_tboi_jupiter = true
}

BI.FOOD_ITEMS = {
    j_gros_michel = true,
    j_ice_cream = true,
    j_cavendish = true,
    j_turtle_bean = true,
    j_popcorn = true,
    j_ramen = true,
    j_seltzer = true,
    j_tboi_lunch = true,
    j_tboi_dinner = true,
    j_tboi_dessert = true,
    j_tboi_breakfast = true,
    j_tboi_rotten_meat = true,
    j_tboi_midnight_snack = true,
}

BI.FAMILIARS = {
    repetitions = 1
}

BI.FLIES = {
    special = {
        Fire = {},
        Fire_explosive = {},
        Poison = {},
        Poison_explosive = {},
        Bleed = {},
        Fear = {},
        Petrify = {},
        Charm = {},
        Slow = {},
        Slow_explosive = {},
        Confusion = {},
        Knockback = {},
        Knockback_confusion_poison = {},
        Magnetic = {},
        Bone = {},
        Godhead = {},
        Holy = {},
        Homing = {},
        Electric = {},
        Shield = {},
        Explosive = {},
        Random = {}
    },
    size = {
        one = 1,
        two = 1.5,
        three = 2,
        four = 2.5,
        half = 0.5,
        tiny = 0.1
    },
    fly_chips = 25,
    fly_mult = 0
}