--- Tables to be used in The Balatro of Isaac

BI.ENABLED_JOKERS = {
    -- Page 1
    "page1/sad_onion",
    "page1/inner_eye",
    "page1/spoon_bender",
    "page1/crickets_head",
    "page1/my_reflection",
    "page1/number_one",
    "page1/blood_of_the_martyr",
    "page1/brother_bobby",
    "page1/skatole",
    "page1/halo_of_flies",
    "page1/1up",
    "page1/magic_mushroom",
    "page1/the_virus",
    "page1/roid_rage",
    "page1/less_than_3",

    -- Page 2
    "page2/raw_liver",
    "page2/skeleton_key",
    "page2/a_dollar",
    "page2/boom",
    "page2/transcendence",
    "page2/the_compass",
    "page2/lunch",
    "page2/dinner",
    "page2/dessert",
    "page2/breakfast",
    "page2/rotten_meat",
    "page2/wooden_spoon",
    "page2/the_belt",
    "page2/moms_underwear",
    "page2/moms_heels",

    -- Page 3
    -- "page3/moms_lipstick",
    -- "page3/wire_coat_hangar",
    -- "page3/the_bible",
    -- "page3/the_book_of_belial",
    -- "page3/the_necronomicon",
    -- "page3/the_poop",
    -- "page3/mr_boom",
    -- "page3/tammys_head",
    -- "page3/moms_bra",
    -- "page3/kamikaze",
    -- "page3/moms_pad",
    -- "page3/bobs_rotten_head",
    -- "page3/teleport",
    -- "page3/yum_heart",
    -- "page3/lucky_foot",

    -- Page 4
    -- "page4/doctors_remote",
    -- "page4/cupids_arrow",
    -- "page4/shoop_da_woop",
    -- "page4/steven",
    -- "page4/pentagram",
    -- "page4/dr_fetus",
    -- "page4/magneto",
    -- "page4/treasure_map",
    -- "page4/moms_eye",
    -- "page4/lemon_mishap",
    -- "page4/distant_admiration",
    -- "page4/book_of_shadows",
    -- "page4/the_ladder",
    -- "page4/charm_of_the_vampire",
    -- "page4/the_battery",

    -- Page 5
    -- "page5/steam_sale",
    -- "page5/anarchist_cookbook",
    -- "page5/the_hourglass",
    -- "page5/sister_maggy",
    -- "page5/technology",
    -- "page5/chocolate_milk",
    -- "page5/growth_hormones",
    -- "page5/mini_mush",
    -- "page5/rosary",
    -- "page5/cube_of_meat",
    -- "page5/a_quarter",
    -- "page5/phd",
    -- "page5/xray_vision",
    -- "page5/my_little_unicorn",
    -- "page5/book_of_revelations",

    -- Page 6
    -- "page6/the_mark",
    -- "page6/the_pact",
    -- "page6/dead_cat",
    -- "page6/lord_of_the_pit",
    -- "page6/the_nail",
    -- "page6/we_need_to_go_deeper",
    -- "page6/deck_of_cards",
    -- "page6/monstros_tooth",
    -- "page6/lokis_horns",
    -- "page6/little_chubby",
    -- "page6/spider_bite",
    -- "page6/the_small_rock",
    -- "page6/spelunker_hat",
    -- "page6/super_bandage",
    -- "page6/the_gamekid",

    -- Page 7
    -- "page7/sack_of_pennies",
    -- "page7/robo_baby",
    -- "page7/little_chad",
    -- "page7/the_book_of_sin",
    -- "page7/the_relic",
    -- "page7/little_gish",
    -- "page7/little_steven",
    -- "page7/the_halo",
    -- "page7/moms_bottle_of_pills",
    -- "page7/the_common_cold",
    -- "page7/the_parasite",
    -- "page7/the_d6",
    -- "page7/mr_mega",
    -- "page7/pinking_shears",
    -- "page7/the_wafer",

    -- Page 8
    -- "page8/money_equals_power",
    -- "page8/moms_contacts",
    -- "page8/the_bean",
    -- "page8/guardian_angel",
    -- "page8/demon_baby",
    -- "page8/moms_knife",
    -- "page8/ouija_board",
    -- "page8/9_volt",
    -- "page8/dead_bird",
    -- "page8/brimstone",
    -- "page8/blood_bag",
    -- "page8/skinny_odd_mushroom",
    -- "page8/fat_odd_mushroom",
    -- "page8/whore_of_babylon",
    -- "page8/monster_manual",

    -- Page 9
    -- "page9/dead_sea_scrolls",
    -- "page9/bobby_bomb",
    -- "page9/razor_blade",
    -- "page9/forget_me_now",
    -- "page9/forever_alone",
    -- "page9/bucket_of_lard",
    -- "page9/a_pony",
    -- "page9/bomb_bag",
    -- "page9/a_lump_of_coal",
    -- "page9/guppys_paw",
    -- "page9/guppys_tail",
    -- "page9/iv_bag",
    -- "page9/best_friend",
    -- "page9/remote_detonator",
    -- "page9/stigmata",

    -- Page 10
    -- "page10/moms_purse",
    -- "page10/bobs_curse",
    -- "page10/pageant_boy",
    -- "page10/scapular",
    -- "page10/speed_ball",
    -- "page10/bum_friend",
    -- "page10/guppys_head",
    -- "page10/prayer_card",
    -- "page10/notched_axe",
    -- "page10/infestation",
    -- "page10/ipecac",
    -- "page10/tough_love",
    -- "page10/the_mulligan",
    -- "page10/technology_2",
    -- "page10/mutant_spider",

    -- Page 11
    -- "page11/chemical_peel",
    -- "page11/the_peeper",
    -- "page11/habit",
    -- "page11/bloody_lust",
    -- "page11/crystal_ball",
    -- "page11/spirit_of_the_night",
    -- "page11/crack_the_sky",
    -- "page11/ankh",
    -- "page11/celtic_cross",
    -- "page11/ghost_baby",
    -- "page11/the_candle",
    -- "page11/cat_o_nine_tails",
    -- "page11/d20",
    -- "page11/harlequin_baby",
    -- "page11/epic_fetus",

    -- Page 12
    -- "page12/polyphemus",
    -- "page12/daddy_longlegs",
    -- "page12/spider_butt",
    -- "page12/sacrificial_dagger",
    -- "page12/mitre",
    -- "page12/rainbow_baby",
    -- "page12/dads_key",
    -- "page12/stem_cells",
    -- "page12/portable_slot",
    -- "page12/holy_water",
    -- "page12/fate",
    -- "page12/the_black_bean",
    -- "page12/white_pony",
    -- "page12/sacred_heart",
    -- "page12/toothpicks",

    -- Page 13
    -- "page13/holy_grail",
    -- "page13/dead_dove",
    -- "page13/blood_rights",
    -- "page13/guppys_hairball",
    -- "page13/abel",
    -- "page13/smb_super_fan",
    -- "page13/pyro",
    -- "page13/3_dollar_bill",
    -- "page13/telepathy_for_dummies",
    -- "page13/meat",
    -- "page13/magic_8_ball",
    -- "page13/moms_coin_purse",
    -- "page13/squeezy",
    -- "page13/jesus_juice",
    -- "page13/box",

    -- Page 14
    -- "page14/moms_key",
    -- "page14/moms_eyeshadow",
    -- "page14/iron_bar",
    -- "page14/midas_touch",
    -- "page14/humbleing_bundle",
    -- "page14/fanny_pack",
    -- "page14/sharp_plug",
    -- "page14/the_guillotine",
    -- "page14/ball_of_bandages",
    -- "page14/champion_belt",
    -- "page14/butt_bombs",
    -- "page14/gnawed_leaf",
    -- "page14/spiderbaby",
    -- "page14/guppys_collar",
    -- "page14/lost_contact",

    -- Page 15
    -- "page15/anemic",
    -- "page15/goat_head",
    -- "page15/ceremonial_robes",
    -- "page15/moms_wig",
    -- "page15/placenta",
    -- "page15/old_bandage",
    -- "page15/sad_bombs",
    -- "page15/rubber_cement",
    -- "page15/anti_gravity",
    -- "page15/pyromaniac",
    -- "page15/crickets_body",
    -- "page15/gimpy",
    -- "page15/black_lotus",
    -- "page15/piggy_bank",
    -- "page15/moms_perfume",

    -- Page 16
    -- "page16/monstros_lung",
    -- "page16/abaddon",
    -- "page16/ball_of_tar",
    -- "page16/stop_watch",
    -- "page16/tiny_planet",
    -- "page16/infestation_2",
    -- "page16/e_coli",
    -- "page16/deaths_touch",
    -- "page16/key_piece_1",
    -- "page16/key_piece_2",
    -- "page16/experimental_treatment",
    -- "page16/contract_from_below",
    -- "page16/infamy",
    -- "page16/trinity_shield",
    -- "page16/tech_point_5",

    -- Page 17
    -- "page17/20_20",
    -- "page17/blue_map",
    -- "page17/bffs",
    -- "page17/hive_mind",
    -- "page17/theres_options",
    -- "page17/bogo_bombs",
    -- "page17/starter_deck",
    -- "page17/little_baggy",
    -- "page17/magic_scab",
    -- "page17/blood_clot",
    -- "page17/screw",
    -- "page17/hot_bombs",
    -- "page17/fire_mind",
    -- "page17/missing_no",
    -- "page17/dark_matter",

    -- Page 18
    -- "page18/black_candle",
    -- "page18/proptosis",
    -- "page18/missing_page_2",
    -- "page18/smart_fly",
    -- "page18/dry_baby",
    -- "page18/juicy_sack",
    -- "page18/robo_baby_2",
    -- "page18/rotten_baby",
    -- "page18/headless_baby",
    -- "page18/leech",
    -- "page18/mystery_sack",
    -- "page18/bbf",
    -- "page18/bobs_brain",
    -- "page18/best_bud",
    -- "page18/lil_brimstone",

    -- Page 19
    -- "page19/isaacs_heart",
    -- "page19/lil_haunt",
    -- "page19/dark_bum",
    -- "page19/big_fan",
    -- "page19/sissy_long_legs",
    -- "page19/punching_bag",
    -- "page19/how_to_jump",
    -- "page19/d100",
    -- "page19/d4",
    -- "page19/d10",
    -- "page19/blank_card",
    -- "page19/book_of_secrets",
    -- "page19/box_of_spiders",
    -- "page19/red_candle",
    -- "page19/the_jar",

    -- Page 20
    -- "page20/flush",
    -- "page20/satanic_bible",
    -- "page20/head_of_krampus",
    -- "page20/butter_bean",
    -- "page20/magic_fingers",
    -- "page20/converter",
    -- "page20/pandoras_box",
    -- "page20/unicorn_stump",
    -- "page20/taurus",
    -- "page20/aries",
    -- "page20/cancer",
    -- "page20/leo",
    -- "page20/virgo",
    -- "page20/libra",
    -- "page20/scorpio",

    -- Page 21
    -- "page21/sagittarius",
    -- "page21/capricorn",
    -- "page21/aquarius",
    -- "page21/pisces",
    -- "page21/eves_mascara",
    -- "page21/judas_shadow",
    -- "page21/maggys_bow",
    -- "page21/holy_mantle",
    -- "page21/thunder_thighs",
    -- "page21/strange_attractor",
    -- "page21/cursed_eye",
    -- "page21/mysterious_liquid",
    -- "page21/gemini",
    -- "page21/cains_other_eye",
    -- "page21/blue_babys_only_friend",

    -- Page 22
    -- "page22/samsons_chains",
    -- "page22/mongo_baby",
    -- "page22/isaacs_tears",
    -- "page22/undefined",
    -- "page22/scissors",
    -- "page22/breath_of_life",
    -- "page22/the_polaroid",
    -- "page22/the_negative",
    -- "page22/the_ludovico_technique",
    -- "page22/soy_milk",
    -- "page22/godhead",
    -- "page22/lazarus_rags",
    -- "page22/the_mind",
    -- "page22/the_body",
    -- "page22/the_soul",

    -- Page 23
    -- "page23/dead_onion",
    -- "page23/broken_watch",
    -- "page23/boomerang",
    -- "page23/safety_pin",
    -- "page23/caffeine_pill",
    -- "page23/torn_photo",
    -- "page23/blue_cap",
    -- "page23/latch_key",
    -- "page23/match_book",
    -- "page23/synthoil",
    -- "page23/a_snack",
    -- "page23/diplopia",
    -- "page23/placebo",
    -- "page23/wooden_nickel",
    -- "page23/toxic_shock",

    -- Page 24
    -- "page24/mega_bean",
    -- "page24/glass_cannon",
    -- "page24/bomber_boy",
    -- "page24/crack_jacks",
    -- "page24/moms_pearls",
    -- "page24/car_battery",
    -- "page24/box_of_friends",
    -- "page24/the_wiz",
    -- "page24/8_inch_nails",
    -- "page24/incubus",
    -- "page24/fates_reward",
    -- "page24/lil_chest",
    -- "page24/sworn_protector",
    -- "page24/friend_zone",
    -- "page24/lost_fly",

    -- Page 25
    -- "page25/scatter_bombs",
    -- "page25/sticky_bombs",
    -- "page25/epiphora",
    -- "page25/continuum",
    -- "page25/mr_dolly",
    -- "page25/curse_of_the_tower",
    -- "page25/charged_baby",
    -- "page25/dead_eye",
    -- "page25/holy_light",
    -- "page25/host_hat",
    -- "page25/restock",
    -- "page25/bursting_sack",
    -- "page25/no_2",
    -- "page25/pupula_duplex",
    -- "page25/pay_to_play",

    -- Page 26
    -- "page26/edens_blessing",
    -- "page26/friendly_ball",
    -- "page26/tear_detonator",
    -- "page26/lil_gurdy",
    -- "page26/bumbo",
    -- "page26/d12",
    -- "page26/censer",
    -- "page26/key_bum",
    -- "page26/rune_bag",
    -- "page26/seraphim",
    -- "page26/betrayal",
    -- "page26/zodiac",
    -- "page26/serpents_kiss",
    -- "page26/marked",
    -- "page26/tech_x",

    -- Page 27
    -- "page27/ventricle_razor",
    -- "page27/tractor_beam",
    -- "page27/gods_flesh",
    -- "page27/maw_of_the_void",
    -- "page27/spear_of_destiny",
    -- "page27/explosivo",
    -- "page27/chaos",
    -- "page27/spider_mod",
    -- "page27/farting_baby",
    -- "page27/gb_bug",
    -- "page27/d8",
    -- "page27/purity",
    -- "page27/athame",
    -- "page27/empty_vessel",
    -- "page27/evil_eye",

    -- Page 28
    -- "page28/lusty_blood",
    -- "page28/cambion_conception",
    -- "page28/immaculate_conception",
    -- "page28/more_options",
    -- "page28/crown_of_light",
    -- "page28/deep_pockets",
    -- "page28/succubus",
    -- "page28/fruit_cake",
    -- "page28/teleport_2",
    -- "page28/black_powder",
    -- "page28/kidney_bean",
    -- "page28/glowing_hour_glass",
    -- "page28/circle_of_protection",
    -- "page28/sack_head",
    -- "page28/night_light",

    -- Page 29
    -- "page29/obsessed_fan",
    -- "page29/mine_crafter",
    -- "page29/pjs",
    -- "page29/head_of_the_keeper",
    -- "page29/papa_fly",
    -- "page29/multidimensional_baby",
    -- "page29/glitter_bombs",
    -- "page29/my_shadow",
    -- "page29/jar_of_flies",
    -- "page29/lil_loki",
    -- "page29/milk",
    -- "page29/d7",
    -- "page29/binky",
    -- "page29/moms_box",
    -- "page29/kidney_stone",

    -- Page 30
    -- "page30/mega_blast",
    -- "page30/dark_princes_crown",
    -- "page30/apple",
    -- "page30/lead_pencil",
    -- "page30/dog_tooth",
    -- "page30/dead_tooth",
    -- "page30/linger_bean",
    -- "page30/shard_of_glass",
    -- "page30/metal_plate",
    -- "page30/eye_of_greed",
    -- "page30/tarot_cloth",
    -- "page30/vericose_veins",
    -- "page30/compound_fracture",
    -- "page30/polydactyly",
    -- "page30/dads_lost_coin",

    -- Page 31
    -- "page31/midnight_snack",
    -- "page31/cone_head",
    -- "page31/belly_button",
    -- "page31/sinus_infection",
    -- "page31/glaucoma",
    -- "page31/parasitoid",
    -- "page31/eye_of_belial",
    -- "page31/sulfuric_acid",
    -- "page31/glyph_of_balance",
    -- "page31/analog_stick",
    -- "page31/contagion",
    -- "page31/finger",
    -- "page31/shade",
    -- "page31/depression",
    -- "page31/hushy",

    -- Page 32
    -- "page32/lil_monstro",
    -- "page32/king_baby",
    -- "page32/big_chubby",
    -- "page32/plan_c",
    -- "page32/d1",
    -- "page32/void",
    -- "page32/pause",
    -- "page32/smelter",
    -- "page32/compost",
    -- "page32/dataminer",
    -- "page32/clicker",
    -- "page32/mama_mega",
    -- "page32/wait_what",
    -- "page32/crooked_penny",
    -- "page32/dull_razor",

    -- Page 33
    -- "page33/potato_peeler",
    -- "page33/metronome",
    -- "page33/d_infinity",
    -- "page33/edens_soul",
    -- "page33/acid_baby",
    -- "page33/yo_listen",
    -- "page33/adrenaline",
    -- "page33/jacobs_ladder",
    -- "page33/ghost_pepper",
    -- "page33/euthanasia",
    -- "page33/camo_undies",
    -- "page33/duality",
    -- "page33/eucharist",
    -- "page33/sack_of_sacks",
    -- "page33/greeds_gullet",

    -- Page 34
    -- "page34/large_zit",
    -- "page34/little_horn",
    -- "page34/brown_nugget",
    -- "page34/poke_go",
    -- "page34/backstabber",
    -- "page34/sharp_straw",
    -- "page34/moms_razor",
    -- "page34/bloodshot_eye",
    -- "page34/delirious",
    -- "page34/angry_fly",
    -- "page34/black_hole",
    -- "page34/bozo",
    -- "page34/broken_modem",
    -- "page34/mystery_gift",
    -- "page34/sprinkler",

    -- Page 35
    -- "page35/fast_bombs",
    -- "page35/buddy_in_a_box",
    -- "page35/lil_delirium",
    -- "page35/jumper_cables",
    -- "page35/coupon",
    -- "page35/telekinesis",
    -- "page35/moving_box",
    -- "page35/technology_zero",
    -- "page35/leprosy",
    -- "page35/7_seals",
    -- "page35/mr_me",
    -- "page35/angelic_prism",
    -- "page35/pop",
    -- "page35/deaths_list",
    -- "page35/haemolacria",

    -- Page 36
    -- "page36/lacryphagy",
    -- "page36/trisagion",
    -- "page36/schoolbag",
    -- "page36/blanket",
    -- "page36/sacrificial_dagger",
    -- "page36/lil_spewer",
    -- "page36/marbles",
    -- "page36/mystery_bag",
    -- "page36/flat_stone",
    -- "page36/marrow",
    -- "page36/slipped_rib",
    -- "page36/hallowed_ground",
    -- "page36/pointy_rib",
    -- "page36/book_of_the_dead",
    -- "page36/dads_ring",

    -- Page 37
    -- "page37/divorce_papers",
    -- "page37/jaw_bone",
    -- "page37/brittle_bones",
    -- "page37/broken_shovel_handle",
    -- "page37/broken_shovel_head",
    -- "page37/moms_shovel",
    -- "page37/clear_rune",
    -- "page37/mucormycosis",
    -- "page37/2spooky",
    -- "page37/golden_razor",
    -- "page37/sulfur",
    -- "page37/fortune_cookie",
    -- "page37/eye_sore",
    -- "page37/120_volt",
    -- "page37/it_hurts",

    -- Page 38
    -- "page38/almond_milk",
    -- "page38/rock_bottom",
    -- "page38/nancy_bombs",
    -- "page38/bar_of_soap",
    -- "page38/blood_puppy",
    -- "page38/dream_catcher",
    -- "page38/pascal_candle",
    -- "page38/divine_intervention",
    -- "page38/blood_oath",
    -- "page38/playdough_cookie",
    -- "page38/orphan_socks",
    -- "page38/eye_of_the_occult",
    -- "page38/immaculate_heart",
    -- "page38/monstrance",
    -- "page38/the_intruder",

    -- Page 39
    -- "page39/dirty_mind",
    -- "page39/damocles",
    -- "page39/free_lemonade",
    -- "page39/spirit_sword",
    -- "page39/red_key",
    -- "page39/psy_fly",
    -- "page39/wavy_cap",
    -- "page39/rocket_in_a_jar",
    -- "page39/book_of_virtues",
    -- "page39/alabaster_box",
    -- "page39/the_stairway",
    -- "page39/sol",
    -- "page39/luna",
    -- "page39/mercurius",
    -- "page39/venus",

    -- Page 40
    -- "page40/terra",
    -- "page40/mars",
    -- "page40/jupiter",
    -- "page40/saturnus",
    -- "page40/uranus",
    -- "page40/neptunus",
    -- "page40/pluto",
    -- "page40/voodoo_head",
    -- "page40/eye_drops",
    -- "page40/act_of_contrition",
    -- "page40/member_card",
    -- "page40/battery_pack",
    -- "page40/moms_bracelet",
    -- "page40/the_scooper",
    -- "page40/ocular_rift",

    -- Page 41
    -- "page41/boiled_baby",
    -- "page41/freezer_baby",
    -- "page41/eternal_d6",
    -- "page41/bird_cage",
    -- "page41/larynx",
    -- "page41/lost_soul",
    -- "page41/blood_bombs",
    -- "page41/lil_dumpy",
    -- "page41/birds_eye",
    -- "page41/lodestone",
    -- "page41/rotten_tomato",
    -- "page41/birthright",
    -- "page41/red_stew",
    -- "page41/genesis",
    -- "page41/sharp_key",

    -- Page 42
    -- "page42/booster_pack",
    -- "page42/mega_mush",
    -- "page42/knife_piece_1",
    -- "page42/knife_piece_2",
    -- "page42/death_certificate",
    -- "page42/bot_fly",
    -- "page42/meat_cleaver",
    -- "page42/evil_charm",
    -- "page42/dogma",
    -- "page42/purgatory",
    -- "page42/stitches",
    -- "page42/r_key",
    -- "page42/knockout_drops",
    -- "page42/eraser",
    -- "page42/yuck_heart",

    -- Page 43
    -- "page43/urn_of_souls",
    -- "page43/akeldama",
    -- "page43/magic_skin",
    -- "page43/revelation",
    -- "page43/consolation_prize",
    -- "page43/tinytoma",
    -- "page43/brimstone_bombs",
    -- "page43/4_point_5_volt",
    -- "page43/fruity_plum",
    -- "page43/plum_flute",
    -- "page43/star_of_bethlehem",
    -- "page43/cube_baby",
    -- "page43/vade_retro",
    -- "page43/false_phd",
    -- "page43/spin_to_win",

    -- Page 44
    -- "page44/vasculitis",
    -- "page44/giant_cell",
    -- "page44/tropicamide",
    -- "page44/card_reading",
    -- "page44/quints",
    -- "page44/tooth_and_nail",
    -- "page44/binge_eater",
    -- "page44/guppys_eye",
    -- "page44/strawman",
    -- "page44/dads_note",
    -- "page44/sausage",
    -- "page44/options_question",
    -- "page44/candy_heart",
    -- "page44/a_pound_of_flesh",
    -- "page44/redemption",

    -- Page 45
    -- "page45/spirit_shackles",
    -- "page45/cracked_orb",
    -- "page45/empty_heart",
    -- "page45/astral_projection",
    -- "page45/c_section",
    -- "page45/lil_abaddon",
    -- "page45/montezumas_revenge",
    -- "page45/lil_portal",
    -- "page45/worm_friend",
    -- "page45/bone_spurs",
    -- "page45/hungry_soul",
    -- "page45/jar_of_wisps",
    -- "page45/soul_locket",
    -- "page45/friend_finder",
    -- "page45/inner_child",

    -- Page 46
    -- "page46/glitched_crown",
    -- "page46/belly_jelly",
    -- "page46/sacred_orb",
    -- "page46/sanguine_bond",
    -- "page46/the_swarm",
    -- "page46/heartbreak",
    -- "page46/bloody_gust",
    -- "page46/salvation",
    -- "page46/vanishing_twin",
    -- "page46/twisted_pair",
    -- "page46/azazels_rage",
    -- "page46/echo_chamber",
    -- "page46/isaacs_tomb",
    -- "page46/vengeful_spirit",
    -- "page46/esau_jr",

    -- Page 47
    -- "page47/berserk",
    -- "page47/dark_arts",
    -- "page47/abyss",
    -- "page47/supper",
    -- "page47/stapler",
    -- "page47/suplex",
    -- "page47/bag_of_crafting",
    -- "page47/flip",
    -- "page47/lemegeton",
    -- "page47/sumptorium",
    -- "page47/recall",
    -- "page47/hold",
    -- "page47/keepers_sack",
    -- "page47/keepers_kin",
    -- "page47/keepers_box",

    -- Page 48
    -- "page48/everything_jar",
    -- "page48/tm_trainer",
    -- "page48/anima_sola",
    -- "page48/spindown_dice",
    -- "page48/hypercoagulation",
    -- "page48/ibs",
    -- "page48/hemoptysis",
    -- "page48/ghost_bombs",
    -- "page48/gello",
    -- "page48/decap_attack",
    -- "page48/glass_eye",
    -- "page48/stye",
    -- "page48/moms_ring",
}

BI.ENABLED_CONSUMABLES = {
    TYPES = {
        "consumable_type"
    },
    ENABLED_REVERSED_TAROTS = {
        "r_fool",
        "r_magician",
        "r_high_priestess",
        "r_empress",
        "r_emperor",
        "r_hierophant",
        "r_lovers",
        "r_chariot",
        "r_justice",
        "r_hermit",
        "r_wheel_of_fortune",
        "r_strength",
        "r_hanged_man",
        "r_death",
        "r_temperance",
        "r_devil",
        "r_tower",
        "r_star",
        "r_moon",
        "r_sun",
        "r_judgement",
        "r_world"
    },
    ENABLED_RUNES = {
        "hagalaz",
        "jera",
        "ehwaz",
        "dagaz",
        "ansuz",
        "perthro",
        "berkano",
        "algiz",
        "blank_rune",
        "black_rune",
        "rune_shard"
    },
    ENABLED_SOUL_STONES = {
        "soul_of_isaac",
        "soul_of_magdalene",
        "soul_of_cain",
        "soul_of_judas",
        "soul_of_blue_baby",
        "soul_of_eve",
        "soul_of_samson",
        "soul_of_azazel",
        "soul_of_lazarus",
        "soul_of_eden",
        "soul_of_lost",
        "soul_of_lilith",
        "soul_of_keeper",
        "soul_of_apollyon",
        "soul_of_forgor",
        "soul_of_bethany",
        "soul_of_jacob_and_esau"
    }
}

BI.POISONOUS = {
    j_tboi_the_virus = true,
    j_tboi_bobs_rotten_head = true,
    j_tboi_the_common_cold = true,
    j_tboi_bobs_curse = true,
    j_tboi_bobs_brain = true,
    j_tboi_mysterious_liquid = true,
    j_tboi_toxic_shock = true,
    j_tboi_serpents_kiss = true,
    j_tboi_sinus_infection = true,
    j_tboi_contagion = true,
    j_tboi_mucormycosis = true,
    j_tboi_jupiter = true
}

BI.FAMILIARS = {
    repetitions = 1
}

BI.FLIES = {
    special = {
        Fire = {},
        Fire_explosive = {},
        Poison = {},
        Poison_explosive = {},
        Bleed = {},
        Fear = {},
        Petrify = {},
        Charm = {},
        Slow = {},
        Slow_explosive = {},
        Confusion = {},
        Knockback = {},
        Knockback_confusion_poison = {},
        Magnetic = {},
        Bone = {},
        Godhead = {},
        Holy = {},
        Homing = {},
        Electric = {},
        Shield = {},
        Explosive = {},
        Random = {}
    },
    size = {
        one = 1,
        two = 1.5,
        three = 2,
        four = 2.5,
        half = 0.5,
        tiny = 0.1
    },
    fly_chips = 25,
    fly_mult = 0
}

BI.IGNORE = {
    CRICKETS_HEAD = {
        j_stencil = true,
        j_misprint = true,
        j_raised_fist = true,
        j_steel_joker = true,
        j_even_steven = true,
        j_ride_the_bus = true,
        j_constellation = true,
        j_green_joker = true,
        j_madness = true,
        j_hologram = true,
        j_obelisk = true,
        j_erosion = true,
        j_fortune_teller = true,
        j_lucky_cat = true,
        j_tousers = true,
        j_ramen = true,
        j_campfire = true,
        j_throwback = true,
        j_glass = true,
        j_hit_the_road = true,
        j_duo = true,
        j_trio = true,
        j_family = true,
        j_order = true,
        j_tribe = true,
        j_shoot_the_moon = true,
        j_canio = true,
        j_yorick = true
    }
}